### PR TITLE
Create spectra-bot block

### LINKED ISSUE #377: [Category Pages] Implement "spectra bot" block
Reference: https://www.moleculardevices.com/products/microplate-readers

The content for this has to be created for this page.

Screenshot 2023-05-17 at 15 32 27

### PR DESCRIPTION
**Pull request by alexcarol**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #377

Test URLs:
- Original: https://www.moleculardevices.com/products/microplate-readers
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/
- After: https://issue-377--moleculardevices--hlxsites.hlx.page/products/microplate-readers/

### CODE REVIEW

**Comment by duynguyen** [comment]
The quote text needs some more padding bottom on mobile. Also could you revise the use of (min / max) height / width? they look a bit complex.

**Comment by lydiapuric** [comment]
+1 same observation as Duy + on mobile the image is broken and misses parts (tried < 759px)

**Comment by jose-correia** [comment]
@alexcarol On mobile, the position of the background image is off, it should fit inside the div, instead of being too big

**Comment by alexcarol** [comment]
> @alexcarol On mobile, the position of the background image is off, it should fit inside the div, instead of being too big

The current behaviour is consistent with the original website, what i'm seeing:
Original: 
image

Franklin:
image

Should we change this behaviour?

**Comment by alexcarol** [comment]
@jose-correia fixed issue, it turned out that the mobile image looks trimmed: https://github.com/hlxsites/moleculardevices/pull/431/files#diff-93c279baff950ef85487dc858a9d937727a0f0ca79a8e57499575c3b9362e7a2, the solution is to use the desktop image for bigger displays, even though that looks a bit off.

**Pull request merged**
