### PR TITLE
Fix breadcrumbs for resource pages globally #1041

### LINKED ISSUE #1041: Fix breadcrumbs for resource pages globally
https://www.moleculardevices.com/en/assets/tutorials-videos/dd/img/automation-high-content-imaging-for-organoid-research

Should be  Home > Resources

image

### PR DESCRIPTION
**Pull request by lydiapuric**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #1041

Test URLs:
**Home > Resources for Cell Counter**
- Before: https://main--moleculardevices--hlxsites.hlx.page/applications/cell-counting/cell-counter-jurkat-cells
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/applications/cell-counting/cell-counter-jurkat-cells

**Home > Resources for Application Note**
- Before: https://main--moleculardevices--hlxsites.hlx.page/en/assets/app-note/br/spectral-fusion-illumination-technology-for-extended-dynamic-range-on-spectramax-i3x-reader
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/en/assets/app-note/br/spectral-fusion-illumination-technology-for-extended-dynamic-range-on-spectramax-i3x-reader

**Home > Resources for Videos & Webinars**
- Before: https://main--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/dd/img/fast-and-simple-3d-spheroid-analysis-using-the-automated-high-content-imaging
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/dd/img/fast-and-simple-3d-spheroid-analysis-using-the-automated-high-content-imaging

- Before: https://main--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/bpd/colony-picking-automation
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/bpd/colony-picking-automation

- Before: https://main--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/dd/img/automation-high-content-imaging-for-organoid-research
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/dd/img/automation-high-content-imaging-for-organoid-research

**Home > Resources for Interactive Demo**
- Before: https://main--moleculardevices--hlxsites.hlx.page/resources/interactive-demo/cloneselect-imager-fl
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/resources/interactive-demo/cloneselect-imager-fl

- Before: https://main--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/br/elisa-workflow
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/en/assets/tutorials-videos/br/elisa-workflow

**Home > Resources > Customer Breakthrough > Title for Customer Breakthrough**
- Before: https://main--moleculardevices--hlxsites.hlx.page/en/assets/customer-breakthrough/dd/img/qorium
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/en/assets/customer-breakthrough/dd/img/qorium

**Other random pages for rechecking other breadcrumb behavior**

Brochure
- Before: https://main--moleculardevices--hlxsites.hlx.page/en/assets/brochures/dd/img/a-life-sciences-company
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/en/assets/brochures/dd/img/a-life-sciences-company

Lab Notes
- Before: https://main--moleculardevices--hlxsites.hlx.page/lab-notes/microplate-readers/gxp-regulated-industry-assessments-of-microplate-readers
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/lab-notes/microplate-readers/gxp-regulated-industry-assessments-of-microplate-readers

News
- Before:  https://main--moleculardevices--hlxsites.hlx.page/newsroom/news/molecular-devices-launches-custom-organoid-line-expansion-service-using-unique-bioprocess-technology-for-high-throughput-applications
- After:  https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/newsroom/news/molecular-devices-launches-custom-organoid-line-expansion-service-using-unique-bioprocess-technology-for-high-throughput-applications

Application
- Before: https://main--moleculardevices--hlxsites.hlx.page/applications/cell-counting
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/applications/cell-counting

Product
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/clone-screening/mammalian-screening/cloneselect-single-cell-printer-series
- After: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/products/clone-screening/mammalian-screening/cloneselect-single-cell-printer-series

### CODE REVIEW

**Comment by andreituicu** [comment]
@lydiapuric looks like the breadcrumb in the following page is broken: https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/newsroom/news/molecular-devices-launches-custom-organoid-line-expansion-service-using-unique-bioprocess-technology-for-high-throughput-applications 

@MeghnaTewari @dev-rajneeshkumar also it is the same situation as with lab notes, although news are `Resources` according to moldev, they had the normal breadcrumb on the drupal site: https://live-md30.pantheonsite.io/newsroom/news/molecular-devices-launches-custom-organoid-line-expansion-service-using-unique-bioprocess-technology-for-high-throughput-applications

**Comment by lydiapuric** [comment]
Thanks @andreituicu Indeed, https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/newsroom/news/molecular-devices-launches-custom-organoid-line-expansion-service-using-unique-bioprocess-technology-for-high-throughput-applications was broken, fixed!

**Comment by lydiapuric** [comment]
@andreituicu https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/newsroom/news/molecular-devices-launches-custom-organoid-line-expansion-service-using-unique-bioprocess-technology-for-high-throughput-applications has even after the change the normal breadcrumb as in live page https://live-md30.pantheonsite.io/newsroom/news/molecular-devices-launches-custom-organoid-line-expansion-service-using-unique-bioprocess-technology-for-high-throughput-applications

**Comment by lydiapuric** [comment]
@MeghnaTewari @dev-rajneeshkumar 

Could you please clarify for which types of Resources specifically we need to update the breadcrumb behaviour? It looks like just doing it for all resources does not match the drupal implementation.

It looks like the Lab Notes although they are resources, on the drupal implementation they are using the usual style of breadcrumbs.
https://live-md30.pantheonsite.io/lab-notes/microplate-readers/gxp-regulated-industry-assessments-of-microplate-readers
https://1041-breadcrumb--moleculardevices--hlxsites.hlx.page/lab-notes/microplate-readers/gxp-regulated-industry-assessments-of-microplate-readers

Also it is the same situation as with lab notes, although news are Resources according to moldev, they had the normal breadcrumb on the drupal site: https://live-md30.pantheonsite.io/newsroom/news/molecular-devices-launches-custom-organoid-line-expansion-service-using-unique-bioprocess-technology-for-high-throughput-applications

Currently following types are defined as Resources, see https://github.com/hlxsites/moleculardevices/blob/main/blocks/resources/resource-mapping.js.

**Comment by lydiapuric** [comment]
Verified by Meghna: https://github.com/hlxsites/moleculardevices/issues/1041#issuecomment-1680574458

**Pull request merged**
