### PR TITLE
chore: implement feature news posts block

### LINKED ISSUE #7: Implement featured posts block
- [x] requires blog posts and index setup
- [ ] Desktop version
- [ ] Mobile version

Sample from home page
Screenshot 2023-02-21 at 11 41 19

### PR DESCRIPTION
**Pull request by mhaack**
Fix #7 

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/
- After: https://featured-news--moleculardevices--hlxsites.hlx.page/
- Test: https://featured-news--moleculardevices--hlxsites.hlx.page/drafts/mhaack/featured-posts

### CODE REVIEW

**Review by jose-correia — APPROVED** [review]
lgtm

**Review by lydiapuric — APPROVED** [review]
LGTM +1

**Review by paolomoz — COMMENTED** [review]
Images are 20px wider than original with equal window size.
This is due to missing margin that in the original page is present in .zoom-effect-wrapper
Space between posts is ok because it is done with a grid and 20px grid-gap

I think that increasing padding left and right for .feature-posts-wrapper would fix it

**Comment by mhaack** [comment]
@lydiapuric on the LHS yes we have to look, this one at least for the homepage should not impact LHS. But I'm checking think I will prepare this in a separate PR.

**Comment by mhaack** [comment]
@lydiapuric on the LHS yes we have to look, this one at least for the homepage should not impact LHS. But I'm checking think I will prepare this in a separate PR.

**Comment by mhaack** [comment]
> Images are 20px wider than original with equal window size. This is due to missing margin that in the original page is present in .zoom-effect-wrapper Space between posts is ok because it is done with a grid and 20px grid-gap I think that increasing padding left and right for .feature-posts-wrapper would fix it
> 
> Also .feature-posts-wrapper doesn't have any space at the top, this might cause the block above to be too close (but this really depends if the block above already has margin/padding bottom

Margins are fixed now.

**Pull request merged**
