### PR TITLE
feat: Implement and Style Video Gallery Pages

### LINKED ISSUE #554: [Video Gallery] Style landing page
Style:

https://main--moleculardevices--hlxsites.hlx.page/video-gallery

Todos:

- style column blocks
- style headlings (h2) in blue, via CSS attached to the theme of the page
- use correct paddings/margins
- add column block variant with horizontal border lines

### LINKED ISSUE #629: [Video Gallery] Implement dedicated block for layout with main video and side videos
Screenshot 2023-06-14 at 09 45 46

Examples:
* https://franklin.moleculardevices.com/video-gallery/microplate-readers
* https://franklin.moleculardevices.com/video-gallery/cellular-imaging-systems

Customer report:
> Videos are missing and large sized thumbnails are being displayed on all the videos gallery category pages

### PR DESCRIPTION
**Pull request by andreituicu**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #629
Fix #554

NOTEs: 

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.live/video-gallery
- After: https://629-prod-videos--moleculardevices--hlxsites.hlx.live/video-gallery

- Before: https://main--moleculardevices--hlxsites.hlx.live/video-gallery/microplate-readers
- After: https://629-prod-videos--moleculardevices--hlxsites.hlx.live/video-gallery/microplate-readers

- Before: https://main--moleculardevices--hlxsites.hlx.live/video-gallery/cellular-imaging-systems
- After: https://629-prod-videos--moleculardevices--hlxsites.hlx.live/video-gallery/cellular-imaging-systems

- Before: https://main--moleculardevices--hlxsites.hlx.live/video-gallery/flipr-system
- After: https://629-prod-videos--moleculardevices--hlxsites.hlx.live/video-gallery/flipr-system

- Before: https://main--moleculardevices--hlxsites.hlx.live/video-gallery/clone-screening
- After: https://629-prod-videos--moleculardevices--hlxsites.hlx.live/video-gallery/clone-screening

- Before: https://main--moleculardevices--hlxsites.hlx.live/video-gallery/axon-patch-clamp
- After: https://629-prod-videos--moleculardevices--hlxsites.hlx.live/video-gallery/axon-patch-clamp

### CODE REVIEW

**Comment by mhaack** [comment]
On mobile landscaping there is a huge layout shift. On initial load it looks like:

IMG_7210

After scrolling it changes and jumps to the correct layout.

**Comment by andreituicu** [comment]
@mhaack is that from the LHS screenshots or you see that locally? I'm not able to reproduce...

**Comment by andreituicu** [comment]
I even tried throttling the network speed and disable the cache. Still not seeing what you have in your screenshot on mobile. 🤔 For you it's like the CSS for Desktop only is applied and the CSS for mobile is not there yet, but I can't get it to reproduce.

**Comment by mhaack** [comment]
@andreituicu locally with iPhone 11.

**Comment by mhaack** [comment]
Thoughts on the vidyard js loading. On the original site it is directly loaded using `<script src="[//play.vidyard.com/embed/v4.js](https://play.vidyard.com/embed/v4.js)" defer async></script>`.

Can't we just add it in `embedVideo` once, after all the intersection observers have been created?

Also our HTML for the video images with lightbox player looks wired

```
<div class="video-wrapper">
  <div class="video-container">
    <div class="vidyard-player-container" uuid="uUqe3yFG3vCLcasHfCPznR" style="margin: auto; width: 100%; height: auto; overflow: hidden; display: block;">
      <div class="vidyard-lightbox-thumbnail vidyard-lightbox-uUqe3yFG3vCLcasHfCPznR" style="max-width: 700px;">
        <div class="vidyard-lightbox-centering" style="padding-bottom: 56.25%;">
          <img class="vidyard-lightbox-image" src="https://play.vidyard.com/uUqe3yFG3vCLcasHfCPznR.jpg" alt="video thumbnail">
          <div type="button" role="button" class="play-button" title="Play video" data-version="1" tabindex="0" aria-label="Play video GxP compliance solutions for GMP-GLP labs. Opens in a modal" style="display: block; background-color: rgb(46, 46, 46);">
            <div class="play-button-size"></div>
            <div class="arrow-size">
              <div class="arrow-size-ratio"></div>
              <div class="arrow"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <img style="width: 100%; margin: auto; display: none;" class="vidyard-player-embed" src="https://play.vidyard.com/uUqe3yFG3vCLcasHfCPznR.jpg" data-uuid="uUqe3yFG3vCLcasHfCPznR" data-v="4" data-width="700" data-height="394" data-autoplay="1" data-type="lightbox" data-rendered="true">
  </div>
</div>
```
The thumbnail img tag is there twice. @paolomoz do you know/remember?

**Comment by andreituicu** [comment]
@mhaack 

I tested with:

iPhone 12Pro:
 * Chrome
 * Safari

Macbook:
 * Chrome
 * Safari
 * Firefox

Samsung Galaxy S23:
 * Chrome

Still can't get it to reproduce... It's as if this CSS is not applied to you, until you scroll (IIUC):
 
https://github.com/hlxsites/moleculardevices/pull/656/files#diff-3b0522212ad6f9f1bd8be373aad4d1e1714bfde5ce09890f321b06e0ddbdbf77R68-R89

**Comment by mhaack** [comment]
> > Thoughts on the vidyard js loading. On the original site it is directly loaded using <script src="[//play.vidyard.com/embed/v4.js](https://play.vidyard.com/embed/v4.js)" defer async></script>.
> 
> This is the pattern we have on all embeds, to use `loadScript`:
> 
> * Twitter: https://github.com/hlxsites/moleculardevices/blob/main/blocks/embed/embed.js#L31
> * Ceros: https://github.com/hlxsites/moleculardevices/blob/main/blocks/embed/embed.js#L51

I know, but they’re loading the JS once works fine. Here we will, with the reload option, load the JS x times. (I know it it browser cached, still seams odd).

**Comment by mhaack** [comment]
@andreituicu I retested a little and I still can reproduce the behavior. I think I know why it happens. 
I see the wrong layout if I scroll slowly. The layout of one video area is wrong until I reach the end of a section. I believe this is due to the intersection observer’s for the videos on the right sight. On the beginning only one or two right side mini thumbnails are visible. The rest is still have `a` tag, which seams the cause. Scrolling down replaces the `a` tag with vidyard `img` which is styled.

**Comment by andreituicu** [comment]
@mhaack Did the latest commit to style the `a` help with shift? I tried to set the dimensions of the anchor tag to be the same as after the vidyard video is replaced.

**Comment by mhaack** [comment]
No can not spot any change, still same behavior.

**Comment by andreituicu** [comment]
@mhaack I did one more try... please let me know if this helped. If not, I think I would need a screen recording if possible, to understand exactly the problem, because I am mostly guessing and changing the CSS according to those guesses...

**Comment by mhaack** [comment]
Here is a screen recording https://www.dropbox.com/s/k3ryyis8ot74ydb/Video%2017.06.23%2C%2014%2045%2023.mp4?dl=0

**Comment by andreituicu** [comment]
@mhaack Thank you! Yes, this confirms it for me... The media queries are no applied on your phone. You are essentially seeing the desktop view. I can't get that to reproduce on any other device.
I tried to do `@media only screen and (max-width:...)` -> `@media(max-width: ...)`, just as another test.

I can only think of two causes:
1. The CSS is cached on your phone to a very old implementation and doesn't contain the media queries
2. That particular version of the browser doesn't process media queries correctly.

If it is 2, the only option I see is for me to implement it using the mobile first approach: write all the CSS without queries for mobile and write the queries for the Desktop view. The thing is, we have lots of media queries across the website... It might be better to pinpoint exactly where the problem comes from.

**Pull request merged**
