### PR TITLE
hero adjustments

### PR DESCRIPTION
**Pull request by paolomoz**
Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.live/about-us
- After: https://hero-adjustments--moleculardevices--hlxsites.hlx.live/about-us

### CODE REVIEW

**Comment by dev-rajneeshkumar** [comment]
Hi @paolomoz desktop looks fine to me but still adjustments needed in  mobile.
Current:
image
Original: 
image

**Comment by paolomoz** [comment]
> Hi @paolomoz desktop looks fine to me but still adjustments needed in mobile. Current: mobile
> 
> Original: image

thanks; min height for small screen was missing. set it to 250px

**Comment by dev-rajneeshkumar** [comment]
Looks better @paolomoz but I think min height should be 180px as per original. Because while comparing both, hero image is cutting off on the edges.
mobile-2
Can be fixed with min-height: 180px
mobile-orig

**Comment by paolomoz** [comment]
> Looks better @paolomoz but I think min height should be 180px as per original. Because while comparing both, hero image is cutting off on the edges. mobile-2 Can be fixed with min-height: 180px mobile-orig

@dev-rajneeshkumar I fixed it with padding. could you check if this resolves your test as well?

**Comment by dev-rajneeshkumar** [comment]
> > Looks better @paolomoz but I think min height should be 180px as per original. Because while comparing both, hero image is cutting off on the edges. mobile-2 Can be fixed with min-height: 180px mobile-orig
> 
> @dev-rajneeshkumar I fixed it with padding. could you check if this resolves your test as well?

Sorry @paolomoz but still not matches with original for me :(

**Comment by paolomoz** [comment]
@dev-rajneeshkumar after our screen share I could reproduce the difference you described and I changed min-height as you suggested. please review/approve if ok

**Review by dev-rajneeshkumar — APPROVED** [review]
Looks good to me @paolomoz

**Pull request merged**
