### PR TITLE
feat - Scroll Blog Filter into view

### PR DESCRIPTION
**Pull request by andreituicu**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Scroll blog filter into view when there is something selected.

Original: https://moleculardevices.com/lab-notes/blog#General

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.live/lab-notes/blog#General
- After: https://blog-list-scroll--moleculardevices--hlxsites.hlx.live/lab-notes/blog#General

### CODE REVIEW

**Comment by lydiapuric** [comment]
@andreituicu In FF it doesn’t scroll as much as on original page, otherwise on Chrome code and scrolling looks good for me.

**Review by lydiapuric — APPROVED** [review]
+1 See minor issue for FF in comments.

**Comment by andreituicu** [comment]
@lydiapuric Should be better now. Could you please have another look? 🙂

**Review by mhaack — APPROVED** [review]

**Review by lydiapuric — APPROVED** [review]
+1

**Pull request merged**
