### PR TITLE
implement generic card component

### LINKED ISSUE #284: Generalize card implementation
We have multiple card styles that can be grouped for unified behaviors and reuse.
- blog card: https://www.moleculardevices.com/lab-notes/blog#viewall
- latest resources: https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers (same as blog card with additional green type)
- applications & research, related products & services: https://www.moleculardevices.com/products/clone-screening
- related products & services (tab): https://www.moleculardevices.com/products/clone-screening/microbial-screening/qpix-400-series-microbial-colony-pickers (same as above with the green subcategory label)
- citations: https://www.moleculardevices.com/citations

The idea is to have a single card implementation working for all card styles while easily adapted for new variations.

### PR DESCRIPTION
**Pull request by duynguyen**
Fix #284 

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page
- After: https://284-generic-card--moleculardevices--hlxsites.hlx.page

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/lab-notes/blog#viewall
- After: https://284-generic-card--moleculardevices--hlxsites.hlx.page/lab-notes/blog#viewall

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers
- After: https://284-generic-card--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/lab-notes/clone-screening/challenges-of-cell-line-development-and-emerging-technologies-to-regulate-monoclonality
- After: https://284-generic-card--moleculardevices--hlxsites.hlx.page/lab-notes/clone-screening/challenges-of-cell-line-development-and-emerging-technologies-to-regulate-monoclonality

### CODE REVIEW

**Review by mhaack — APPROVED** [review]
LGTM but please fix the lint errors

**Comment by mhaack** [comment]
I also cross checked the carousels here: https://284-generic-card--moleculardevices--hlxsites.hlx.page/products/clone-screening 👍

**Comment by duynguyen** [comment]
thanks @mhaack . Fixed lint errors.

**Comment by andreituicu** [comment]
I missed this PR. Just to set the expectation of this comment: I'm not trying to say we need to change it, or revert it, just provide my opinion. 🙂

I see how it is more reusable like this, but at the same time, the resulting code has a ton of conditions which makes it hard to read. https://github.com/hlxsites/moleculardevices/pull/290/files#diff-7c4fb3ca668ff89fd64dbab51fbcb4df0437745d7efb143ef3244b268017e19aR33-R71

My personal preference would have maybe rather been for something in between, like:
* 1 common CSS file
* 2 / multiple rendering functions like (`renderCardType1`, `renderCardType2`, or better names if possible? 🙂 ) like so, but using the common CSS classes and keep the rendering JS simple like:
  * https://github.com/hlxsites/moleculardevices/pull/290/files#diff-d78c93210951e446611a6ffa4dd8cbdf09f21720a2bcce23e792c06f706a2a57L17-L40
  * https://github.com/hlxsites/moleculardevices/pull/290/files#diff-ab491c968051f56dabc9994d41477a2afafa56ad6231176b86026d184c4bcde2L57-L74

to make the JS as readable and as easy to understand as possible at glance.

once more, no need to change it now that it is in place. 👍

**Comment by mhaack** [comment]
Wrt 2 multiple rendering functions: this was my initial thinking as well. With the current approach we need less lines of code so I liked the proposal. While I see the point the more `if` and special cases we will get even harder to read. Multiple rendering will also make it more explicit and easy to understand which render card style is applied. So lets keep that option on the table and add if needed.

**Pull request merged**
