### PR TITLE
Publication overview

### LINKED ISSUE #10: Implement press release & "in the news" overview pages
- [ ] setup index containing the press release & in the news docs, index the template field
- [ ] create separate, filtered sheets for press releases & in the news entries
- [ ] implement "list block" used on both pages, with pre filtering config in the doc for types to be displayed

See Press Releases: https://www.moleculardevices.com/newsroom/news
See in the news: https://www.moleculardevices.com/newsroom/in-the-news

### PR DESCRIPTION
**Pull request by lydiapuric**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #10

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.live/newsroom/news
- After: https://publication-overview--moleculardevices--hlxsites.hlx.page/newsroom/news

and 
- Before: https://main--moleculardevices--hlxsites.hlx.live/newsroom/in-the-news
- After: https://publication-overview--moleculardevices--hlxsites.hlx.page/newsroom/in-the-news

### CODE REVIEW

**Comment by paolomoz** [comment]
@lydiapuric some notes:

looking at 
https://publication-overview--moleculardevices--hlxsites.hlx.live/newsroom/news
versus
https://www.moleculardevices.com/newsroom/news

- content background is white in branch and #f0f1f2 in original
- margin between hero and news sections is 37px larger in original (it might be due to the next point)
- .list > .items > .item should not have padding-left
- images are 10px larger than original
- margin between left and right columns is 
- .panel.title border-bottom is 10px larger on the right compared to .select border-bottom

**Comment by paolomoz** [comment]
@lydiapuric latest changes are ok.

There is one big difference: when you select a Year from the left filter, the whole page gets reloaded, while in the original (and that is also much more user friendly) only the search result section (or main) is reloaded. And if the filter selection was done below the fold compared to the top of the search results, it even automatically re-scrolls the page to start with the top of the search results.

**Comment by paolomoz** [comment]
@lydiapuric I also committed this small change as the grey background was not applied to the whole width
https://github.com/hlxsites/moleculardevices/pull/170/commits/df2c70f386d41555bf200ac6de6ca05ad630dad4

**Comment by lydiapuric** [comment]
@paolomoz |
> There is one big difference: when you select a Year from the left filter, the whole page gets reloaded, while in the original (and that is also much more user friendly) only the search result section (or main) is reloaded. And if the filter selection was done below the fold compared to the top of the search results, it even automatically re-scrolls the page to start with the top of the search results.

This is the AJAX loading missing what @kapildhiman  mentioned. He is ok to address AJAX implementation in an up following task.

**Review by paolomoz — APPROVED** [review]

**Comment by mhaack** [comment]
https://publication-overview--moleculardevices--hlxsites.hlx.live/newsroom/in-the-news has some background color issue for me? only the center area is grey background?

**Comment by lydiapuric** [comment]
Hmm, background issue for publication overview is only in FF. Rechecking...

**Comment by paolomoz** [comment]
@lydiapuric the only difference I see is:
+ when you select a filter it scrolls both up or down positioning the top of the results at the top of the page.
+ the original instead does it ONLY if you are already below the fold; hence the original only scrolls up and never down

**Pull request merged**
