### PR TITLE
improve h2 global styling

### LINKED ISSUE #254: Fix heading 2 margins and padding
Our margins and padding on the headlines globally are wrong, see examples:

* https://main--moleculardevices--hlxsites.hlx.page/en/assets/customer-breakthrough/dd/img/visikol
* https://main--moleculardevices--hlxsites.hlx.page/products/assay-kits/cardiotox/earlytox-cardiotoxicity-kit#data
* https://main--moleculardevices--hlxsites.hlx.page/about-us
* https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-m-series-readers

- [x] fix h2 button margin/padding
- [x] fix h2 top marging/padding
- [ ] fix h2 alignment
- [ ] fix h2 font-size and spacing in blocks in different sections used in different page types

### PR DESCRIPTION
**Pull request by lydiapuric**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #254

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/en/assets/customer-breakthrough/dd/img/visikol
- After: https://h2--moleculardevices--hlxsites.hlx.page/en/assets/customer-breakthrough/dd/img/visikol
AND
- Before: https://main--moleculardevices--hlxsites.hlx.page/about-us
- After: https://h2--moleculardevices--hlxsites.hlx.page/about-us
AND
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-m-series-readers
- After: https://h2--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-m-series-readers
AND
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/assay-kits/cell-viability/earlytox-cell-viability-assay-kits
- After: https://h2--moleculardevices--hlxsites.hlx.page/products/assay-kits/cell-viability/earlytox-cell-viability-assay-kits
AND 
- Before: https://main--moleculardevices--hlxsites.hlx.page/products/clone-screening
- After: https://h2--moleculardevices--hlxsites.hlx.page/products/clone-screening

### CODE REVIEW

**Comment by mhaack** [comment]
LGTM on desktop. Please also check on mobile, I think here font-size is too large I think.

**Comment by lydiapuric** [comment]
Thanks @mhaack The font sizes seem not to be yet correct for h2, I focused on spacing, happy to add the check for sizes in this PR.

**Comment by duynguyen** [comment]
there is also diff. spacing for other screen sizes (mobile, etc.) Would it be tackled in this PR?

**Comment by lydiapuric** [comment]
@duynguyen Yes

**Comment by lydiapuric** [comment]
@mhaack @dev-rajneeshkumar @duynguyen 
Improved in the meantime now the mentioned issues.

**Comment by dev-rajneeshkumar** [comment]
image
Hi @lydiapuric  last 2 from my mentions LGTM but first one is still there. Can you please ss from original?

**Comment by mhaack** [comment]
This one looks still little off https://h2--moleculardevices--hlxsites.hlx.page/products/assay-kits/cell-viability/earlytox-cell-viability-assay-kits

Only on mobile the first h2 looks thinner than the following h2.

**Comment by lydiapuric** [comment]
@mhaack https://h2--moleculardevices--hlxsites.hlx.page/products/assay-kits/cell-viability/earlytox-cell-viability-assay-kits is completely off and the thing is, it looks like we didn't work on this style of products yet. I will look over this one again, to improve this. I fear there will be still other pages which might be that off.
@dev-rajneeshkumar H2 alignment is off as per original and we don't plan exactly to mirror that. The point is that the original page made enough exceptions with multiple classes we will not reflect. This can be done in another phase - as of now it's improved, and it will be hard to address all the little styling issues. Do you have additional pages as example where the page is completely off?

**Comment by mhaack** [comment]
@lydiapuric for the product pages just focus on the h2. The rest we will do via separate issues.

**Comment by lydiapuric** [comment]
@dev-rajneeshkumar 
H2 alignment is off as per original
The alignment is not consistent over the pages, so this will have to be addressed with another PR, maybe introducing templates.
Margin/gap from the top of section is fine. But what about Margin/gap from the bottom of the section? As questioned by me in our yesterday's Dvsync call, are we going cover in this PR only?
I addressed some of them, not sure if I managed them all. Can you please recheck?

**Review by mhaack — APPROVED** [review]

**Pull request merged**
