### PR TITLE
Add header cards component

### PR DESCRIPTION
**Pull request by jose-correia**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Screenshot 2023-03-31 at 17 01 25

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/
- After: https://header-cards-component--moleculardevices--hlxsites.hlx.page/

### CODE REVIEW

**Review by lydiapuric — CHANGES_REQUESTED** [review]
As discussed in Slack,
- there is a resizing issue and
- the font size does not match in a smaller screen

**Comment by lydiapuric** [comment]
Except that in FF there is still the background missing, changes and code look ok for me.

**Comment by jose-correia** [comment]
@lydiapuric it seems firefox does not support the `has` CSS attribute. I changed the implementation and now its working 👍

**Comment by lydiapuric** [comment]
Confirmed. PR to be approved.

**Review by lydiapuric — APPROVED** [review]
+1

**Pull request merged**
