### PR TITLE
embed code changes in news

### PR DESCRIPTION
**Pull request by dev-rajneeshkumar**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--moleculardevices--hlxsites.hlx.page/newsroom/in-the-news/quality-assurance-in-drug-discovery

- After: https://embed-code--moleculardevices--hlxsites.hlx.page/newsroom/in-the-news/quality-assurance-in-drug-discovery

### CODE REVIEW

**Review by mhaack — CHANGES_REQUESTED** [review]
This has bunch of lint issues and seams broken

**Comment by mhaack** [comment]
Why is this PR needed? If a news link https://embed-code--moleculardevices--hlxsites.hlx.page/newsroom/in-the-news/quality-assurance-in-drug-discovery uses the embed block it should just work?

**Comment by dev-rajneeshkumar** [comment]
> This has bunch of lint issues and seams broken

yes working on those

**Comment by dev-rajneeshkumar** [comment]
> Why is this PR needed? If a news link https://embed-code--moleculardevices--hlxsites.hlx.page/newsroom/in-the-news/quality-assurance-in-drug-discovery uses the embed block it should just work?

Hi @mhaack embed with sound(https://w.soundcloud.com/player/?) cloud was not working in news page so did this change. Created below funtion to support all
function decorateEmbed(elems) {
  elems.forEach((elem) => {
    const embedUrl = elem.querySelector('a');
    loadEmbed(elem, embedUrl.href);
    embedUrl.remove();
  });

**Review by mhaack — APPROVED** [review]

**Pull request merged**
