### PR TITLE
Issue 548 - Implement video gallery version of cards

### LINKED ISSUE #548: [Video Gallery] Implement video gallery version of cards
## Version 1

Screenshot 2023-06-02 at 17 24 48

Pages:

- https://main--moleculardevices--hlxsites.hlx.page/video-gallery/axon-patch-clamp
- https://main--moleculardevices--hlxsites.hlx.page/video-gallery/cellular-imaging-systems
- https://main--moleculardevices--hlxsites.hlx.page/video-gallery/clone-screening
- https://main--moleculardevices--hlxsites.hlx.page/video-gallery/microplate-readers

## Version 2

Screenshot 2023-06-02 at 18 34 33

Page:

- https://franklin.moleculardevices.com/video-gallery

### PR DESCRIPTION
**Pull request by alexcarol**
Fix #548 

Test URLs:
Version 1 video gallery:
Original: https://www.moleculardevices.com/video-gallery/axon-patch-clamp
Before: https://main--moleculardevices--hlxsites.hlx.page/video-gallery/axon-patch-clamp
After: https://issue-548--moleculardevices--hlxsites.hlx.page/video-gallery/axon-patch-clamp

Version 2 video gallery:
Original: https://www.moleculardevices.com/video-gallery
Before: https://main--moleculardevices--hlxsites.hlx.page/video-gallery
After: https://issue-548--moleculardevices--hlxsites.hlx.page/video-gallery

Microplate readers (UI unchanged, but code refactored to allow reuse):
Before: https://main--moleculardevices--hlxsites.hlx.page/products/microplate-readers
After: https://issue-548--moleculardevices--hlxsites.hlx.page/products/microplate-readers

### CODE REVIEW

**Review by duynguyen — APPROVED** [review]
LGTM.

Minor issue: for variant 1 when you hover the card, the content inside transforms a bit bigger, but the outer card size should remain.

**Comment by mhaack** [comment]
LGTM, some minor style issues on variant 2 (https://issue-548--moleculardevices--hlxsites.hlx.page/video-gallery)
Screenshot 2023-06-06 at 18 26 47

**Comment by alexcarol** [comment]
> LGTM, some minor style issues on variant 2 (https://issue-548--moleculardevices--hlxsites.hlx.page/video-gallery) Screenshot 2023-06-06 at 18 26 47

Fixed

**Comment by alexcarol** [comment]
> LGTM.
> 
> Minor issue: for variant 1 when you hover the card, the content inside transforms a bit bigger, but the outer card size should remain.

Good catch, fixed

**Pull request merged**
